# permissions for end users to edit envoyconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: envoyconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: envoy-controller
    app.kubernetes.io/part-of: envoy-controller
    app.kubernetes.io/managed-by: kustomize
  name: envoyconfig-editor-role
rules:
- apiGroups:
  - mesh.example.com
  resources:
  - envoyconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.example.com
  resources:
  - envoyconfigs/status
  verbs:
  - get
